locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
subtitle                 : "web programming"
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://201904269.github.io/webhomework/"
baseurl                  : ""
